-- Baseline generated by drizzle-kit from src/db/schema.ts, made idempotent by hand so it also adopts databases
-- created by the previous hand-written migrations (001_init.sql, 002_drop_display_name.sql).
CREATE TABLE IF NOT EXISTS "logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_id" uuid NOT NULL,
	"permalink" text NOT NULL,
	"url" text NOT NULL,
	"boss_name" text NOT NULL,
	"boss_icon" text,
	"trigger_id" integer,
	"encounter_key" text,
	"group_id" text,
	"category" text NOT NULL,
	"success" boolean NOT NULL,
	"is_cm" boolean DEFAULT false NOT NULL,
	"is_legendary_cm" boolean DEFAULT false NOT NULL,
	"duration_ms" integer NOT NULL,
	"boss_health_left" real,
	"encounter_time" timestamp with time zone NOT NULL,
	"recorded_by" text,
	"gw2_build" integer,
	"elite_insights_version" text,
	"players" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"accounts" text[] DEFAULT '{}' NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "logs_owner_id_permalink_key" UNIQUE("owner_id","permalink")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"gw2_account" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "logs" DROP CONSTRAINT IF EXISTS "logs_owner_id_fkey";--> statement-breakpoint
ALTER TABLE "logs" ADD CONSTRAINT "logs_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "logs_owner_time_idx" ON "logs" USING btree ("owner_id","encounter_time" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_lower_idx" ON "users" USING btree (lower("email"));--> statement-breakpoint
-- Leftovers of the previous migration setup.
ALTER TABLE "users" DROP COLUMN IF EXISTS "display_name";--> statement-breakpoint
DROP TABLE IF EXISTS "schema_migrations";
