/** IPC channel names shared by main and preload. */
export const IPC = {
  getState: "state:get",
  stateChanged: "state:changed",
  login: "auth:login",
  startBrowserLogin: "auth:browser-login:start",
  cancelBrowserLogin: "auth:browser-login:cancel",
  logout: "auth:logout",
  saveSettings: "settings:save",
  chooseLogFolder: "settings:choose-log-folder",
  startWatching: "watch:start",
  stopWatching: "watch:stop",
  startSession: "session:start",
  renameSession: "session:rename",
  endSession: "session:end",
  resumeSession: "session:resume",
  uploadFiles: "uploads:pick-files",
  clearFinished: "uploads:clear-finished",
  openExternal: "shell:open-external",
  installUpdate: "update:install",
} as const;
